### ISSUE TITLE
Sklearn wrapper break with Scipy on Python 3

### ISSUE THREAD

**Issue by nwilbert** [mdp-toolkit/mdp-toolkit#12]
Line 354 in `scikits_nodes` seems to be the problem: It tries to use `__func__` on a method function (and this is apparently only available on the descriptor on instances of the class).

Apparently this is a problem with the 2to3 translation, the original Python 2 code uses `im_fun`.

I'm not sure what the best approach for fixing this would be (maybe we have to find a workaround for 2to3).

I had the problem on Python 3.3.5 (installed on OSX Mavericks with brew), with sklearn 0.14.1 and scipy 0.13.3.

**Comment by otizonaizit** [comment]
fixed in 21d6ae8c2e8e63ff08cbf7d07249885ff6459285
