### ISSUE TITLE
SFANode eigenvalue issue

### ISSUE THREAD

**Issue by fabschon** [mdp-toolkit/mdp-toolkit#28]
**Summary**

Training SFA nodes often fails when there are redundant dimensions in the training data. This has been a commonly encountered issue for people starting out with SFA for a long time now. Since the SFA implementation is a feature of **mdp** that distinguishes it from similar libraries, the access to its functionality should be as smooth and straightforward as we can possibly make it.

**Problem details**

The `SFANode._stop_training()` method concludes the training of an SFA node by solving a generalized eigenvalue problem using the system's `symeig()` routine. This call fails if the covariance matrix of the data yields eigenvalues close to (or even below) zero and provides the user with an error message that contains insufficient information to help newcomers identify and solve the problem.

While the training data might not be sufficient for the `symeig()` routine, there are workarounds that allow SFA to still be able to extract slow features. In fact, many people reading this might already have their personal workaround / fix, such as slotting a PCA node in front, or using SVD or a different eigenvalue routine to circumvent this issue instead of going back to "fix" their training data.

For an updated SFANode the default behavior does not have to change. However, a workaround such as using SVD should be readily available. Error handling should be fleshed out to an extent that allows (new) users to make an informed decision about how to identify the problem and what to do about it (including possible trade offs of different solutions made available by **mdp**).

**Status**

As of right now there are multiple workarounds already in circulation; a working SVD implementation is also available. In order to include this in **mdp** we need to agree on how to implement a fix (i.e., what should the default behavior be and what solution should be made available) and possibly profile and compare more than one solution to decide which slots into the node most favorably.

**Comment by Stewori** [comment]
This was fixed with https://github.com/mdp-toolkit/mdp-toolkit/commit/6dbfb10a03173315a4fff7a9dfc0d60388df0894. So closing...
