### ISSUE TITLE
Cannot import latest mdp using python 3

### ISSUE THREAD

**Issue by AlbertoEsc** [mdp-toolkit/mdp-toolkit#32]
The latest version of mdp is imported properly when using python 2, but when I try to import mdp using python 3 I get the following exception:

> $ python3 -c "import mdp"
> Traceback (most recent call last):
>  File "<string>", line 1, in <module>
>  File "/home/escalafl/MDP_Fork_AlbertoEsc/mdp-toolkit/mdp/__init__.py", line 131, in <module>
>    from . import utils
>  File "/home/escalafl/MDP_Fork_AlbertoEsc/mdp-toolkit/mdp/utils/__init__.py", line 36, in <module>
>    from .symeig_semidefinite import (symeig_semidefinite_reg,
>  File "/home/escalafl/MDP_Fork_AlbertoEsc/mdp-toolkit/mdp/utils/symeig_semidefinite.py", line 58, in <module>
>    from _symeig import SymeigException
>ImportError: No module named '_symeig'

Apparently this is related to (the absence of) relative imports in python3 and the easiest fix is to change "from _symeig import SymeigException" to "from ._symeig import SymeigException" (an extra period) in symeig_semidefinite.py

**Comment by Stewori** [comment]
Oh, sorry, I guess this was my fault. Forgot to test symeig_semidefinite with Python3. I will fix it as soon as possible.

**Comment by Stewori** [comment]
Fixed in https://github.com/mdp-toolkit/mdp-toolkit/pull/33. While testing on Python 3 I encountered 58 failing tests. And I thought mdp was already Python 3 proof... :(
Or do I have some misconfiguration?

**Comment by Stewori** [comment]
Maybe it's because of an old NumPy version in my Python 3 setup...
