### ISSUE TITLE
Several tests fail under Python 3

### ISSUE THREAD

**Issue by AlbertoEsc** [mdp-toolkit/mdp-toolkit#34]
As some of you have already noticed, several tests fail under python3. When running `python3 setup.py test` I get 59 failed tests with python 3.4.3:  `====== 59 failed, 730 passed, 17 skipped, 490 warnings in 120.83 seconds =======`

The failing tests involve mostly the new online nodes/flows, and they originate mostly from using xrange. Also about 3 tests fail due to using float division instead of integer division. There is a pending pull request involving online nodes, but afaik it does not solve this and is itself also not fully python3 compatible. 

If you want I can send a small pull request that fixes the current incompatibilities. Or, is there any plan on how to proceed with the failing tests?

**Comment by Stewori** [comment]
I think, fixing Python 3 compatibility is an important improvement. I saw the failures too, but so far had other priorities. If you can fix it, that would be great! If there are concerns from core devs, I would happily merge this in.

**Comment by Stewori** [comment]
Thanks for the fix! I confirmed that all tests pass now on Python 2 and 3. Maybe we can add Python 3 now to Travis config? Thoughts?

**Comment by Stewori** [comment]
Looking at travis.yml, MDP seems to use a hack to enable numpy and scipy on Travis. I don't know how to enable Python 3 testing based on this hack, so deferring this to a new issue: https://github.com/mdp-toolkit/mdp-toolkit/issues/36.
I suppose this one can be closed now...
