### ISSUE TITLE
Travis CI testing broken

### ISSUE THREAD

**Issue by Stewori** [mdp-toolkit/mdp-toolkit#44]
See
https://travis-ci.org/mdp-toolkit/mdp-toolkit/builds/481630084?utm_source=github_status&utm_medium=notification

This was triggered by merging #42, but the tests of #42 went fine. So this issue is obviously not caused by changes in #42, but by changes in Travis. It looks like something is wrong with pytest...? Maybe a new release of pytest had backward-breaking changes?

I googled for the prominent feature of the erroneous Travis log: "INTERNALERROR".
This found i.a. https://github.com/ansible/pytest-mp/issues/8, which is about a somewhat similar phenomenon and there it was due to pytest.

Ideas?

**Comment by Debilski** [comment]
The [`pytest_namespace` hook](
https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/conftest.py) is [removed in pytest 4.0](
http://doc.pytest.org/en/latest/deprecations.html). As this function only creates a temporary directory and sets a configuration variable, it might be possible to implement a workaround with `pytest_configure`.

**Comment by NiMlr** [comment]
Thanks for the hint! I have included a possible fix in our pending pull-request. Builds pass. Please check it out.

**Comment by Stewori** [comment]
@Debilski, @NiMlr thanks for the hints and thanks for fixing!

@NiMlr 
Looking at https://github.com/mdp-toolkit/mdp-toolkit/pull/43/files/41a830083cb895950ba50ac2ed7275af0139b8b7..e21cc78162fd76eb40c5b42ba8cc846ba2ffe872#diff-d5a83bfad7a377f90b9865d9f76c7894L60
you just remove the tempdir setup. It's not there for nothing, is it?
I think we should restore the code at the end of ``pytest_configure`` like @Debilski suggests (below https://github.com/mdp-toolkit/mdp-toolkit/pull/43/files/41a830083cb895950ba50ac2ed7275af0139b8b7..e21cc78162fd76eb40c5b42ba8cc846ba2ffe872#diff-d5a83bfad7a377f90b9865d9f76c7894R21).
Turn the line
``return dict(mdp_tempdirname=dirname)``
into
``pytest.mdp_tempdirname=dirname``
like suggested in https://docs.pytest.org/en/latest/deprecations.html#pytest-namespace
(for mdp and bimdp respectively)

**Comment by NiMlr** [comment]
@Stewori Have you seen the subsequent commits?

**Comment by Stewori** [comment]
Sorry, I just followed your link and overlooked that there are subsequent PRs. The final solution looks good to me.
