### ISSUE TITLE
Warnings in tests

### ISSUE THREAD

**Issue by NiMlr** [mdp-toolkit/mdp-toolkit#61]
I collected a list of warnings popping up in different tests. Some may be relevant only to some version combinations of the dependencies.

#### MDP
- [x] `DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.`
appearing in [test_EtaComputerNode.py line 6](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_EtaComputerNode.py#L6) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784648?utm_medium=notification&utm_source=github_status).

- [x] ``DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly``
appearing in [signal_node.py line 180](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/signal_node.py#L180) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status). There are more instances in the code where `formatargspec` is used.

- [x] `FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status).

- [x] ` FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status).

- [x] `ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status).

- [x] `FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
    "avoid this warning.", FutureWarning)`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status).

- [x] `FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status).

- [x] `ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
    % self.max_iter, ConvergenceWarning)`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784645?utm_medium=notification&utm_source=github_status).

- [x] `FutureWarning: The default value of strategy will change from stratified to prior in 0.24.`
appearing in tests of scikit-learn-nodes in [test_nodes_generic.py](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/mdp/test/test_nodes_generic.py#L193) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624814368?utm_medium=notification&utm_source=github_status).

#### BIMDP
- [x] `DeprecationWarning: generator '_execute' raised StopIteration`
       appearing in [binode.py line 529](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/bimdp/binode.py#L529) and [binode.py line 554](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/bimdp/binode.py#L554) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784648?utm_medium=notification&utm_source=github_status).

- [x] `FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.`
      appearing in [test_gradient.py line 107](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/bimdp/test/test_gradient.py#L107) and [test_gradient.py line 109](https://github.com/mdp-toolkit/mdp-toolkit/blob/master/bimdp/test/test_gradient.py#L109) in this [test run](https://travis-ci.org/mdp-toolkit/mdp-toolkit/jobs/624784648?utm_medium=notification&utm_source=github_status).

**Comment by otizonaizit** [comment]
All remaining warnings are fixed by #74
