### ISSUE TITLE
pytest 5

### ISSUE THREAD

**Issue by Stewori** [mdp-toolkit/mdp-toolkit#66]
Upgrading to pytest 5 yields a couple of breakages. This is a non-goal for the upcoming release, but I open this issue to start tracking and hopefully fixing the breakages.

For details see the [Travis logs](https://travis-ci.org/mdp-toolkit/mdp-toolkit/builds/625073440?utm_source=github_status&utm_medium=notification) and https://github.com/mdp-toolkit/mdp-toolkit/pull/65

**Comment by otizonaizit** [comment]
Fixed in #74
